// Generates the native Auth app's parity data from the server reference key-file.js (EMAIL-KEY-CONTRACT-v2 v2.3:
// "the Dart parser must accept and refuse exactly what it does"). SYNTHETIC inputs only: public test secrets, never an
// owner's key. No network. Writes two files (run `dart format` on them afterwards):
//   lib/services/lidar_js_case.dart              the code points JavaScript's toLowerCase changes (EMAIL rule)
//   test/lidar_key_file_parity_extra.dart        more reference verdicts (URI spellings, EMAIL letters, NAMEs)
// Usage (from mobile/apps/auth):
//   node scripts/lidar_key_file_parity.mjs <path to lk-ov-emailkey/public/shared/owner/key-file.js> <label>
// <label> names the reference in the generated headers, e.g. "key-file.js @ d271178 (unchanged since 372ed20)".
import { writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const [refPath, label] = process.argv.slice(2);
if (!refPath || !label) throw new Error('usage: node scripts/lidar_key_file_parity.mjs <key-file.js> <label>');
const { parseKeyFile, keyOtpauthUri } = await import(pathToFileURL(refPath).href);

// ---- 1. JavaScript's toLowerCase, as runs { start, end, step } (step 1 or 2) over every code point it changes.
const changed = [];
for (let cp = 0; cp <= 0x10ffff; cp++) {
  if (cp >= 0xd800 && cp <= 0xdfff) continue;
  const ch = String.fromCodePoint(cp);
  if (ch.toLowerCase() !== ch) changed.push(cp);
}
const runs = [];
for (const cp of changed) {
  const r = runs[runs.length - 1];
  if (r && r.end === r.start && (cp - r.end === 1 || cp - r.end === 2)) { r.step = cp - r.end; r.end = cp; }
  else if (r && r.end !== r.start && cp - r.end === r.step) r.end = cp;
  else runs.push({ start: cp, end: cp, step: 1 });
}
const inRuns = cp => runs.some(r => cp >= r.start && cp <= r.end && (cp - r.start) % r.step === 0);
const changedSet = new Set(changed);
for (let cp = 0; cp <= 0x10ffff; cp++) {
  if (cp >= 0xd800 && cp <= 0xdfff) continue;
  if (inRuns(cp) !== changedSet.has(cp)) throw new Error(`run table wrong at U+${cp.toString(16)}`);
}
const flat = runs.flatMap(r => [r.start, r.end, r.step]).map(n => `0x${n.toString(16).toUpperCase()}`);
writeFileSync(new URL('../lib/services/lidar_js_case.dart', import.meta.url), `// GENERATED by scripts/lidar_key_file_parity.mjs (Node ${process.versions.node}, V8 ${process.versions.v8},
// ICU ${process.versions.icu}, Unicode ${process.versions.unicode}). Do not edit by hand.
//
// Every code point whose JavaScript String.prototype.toLowerCase is not itself, as runs of
// (first, last, step). The server's key-file.js refuses an EMAIL that toLowerCase changes; Dart's own
// toLowerCase uses older Unicode tables, so the Dart parser uses this table instead (contract v2.3 parity).
// ${changed.length} code points in ${runs.length} runs.
const lidarJsLowerCaseRuns = <int>[
  ${flat.join(', ')},
];
`);

// ---- 2. Reference verdicts for spellings the first table (lidar_key_file_parity_cases.dart) does not cover.
const S = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
const Q = `secret=${S}&issuer=LiDAR-Knight&algorithm=SHA1&digits=6&period=30`;
const v2 = ({ name = 'CT', email = 'ct@example.com', uri } = {}) => [
  'LK_FORMAT=2', 'ISSUER=admin.lidarknight.com', 'SEAT=admin2', `NAME="${name}"`, `EMAIL=${email}`, 'GENERATION=4',
  'ISSUED_AT=2026-10-05T12:00:00Z', 'ACTIVATE_BY=2026-10-12T12:00:00Z', 'ACTIVATION_ID=act_0123456789abcdefABCDEF',
  `TOTP_SECRET=${S}`, `OTPAUTH_URI=${uri ?? keyOtpauthUri(name, S)}`,
].join('\n') + '\n';
const L = 'otpauth://totp/LiDAR-Knight:CT';
const cases = [];
const add = (id, text) => cases.push({ id, text });

// OTPAUTH_URI: ports (WHATWG refuses above 65535)
add('v2 URI port 65535', v2({ uri: `otpauth://totp:65535/LiDAR-Knight:CT?${Q}` }));
add('v2 URI port 65536', v2({ uri: `otpauth://totp:65536/LiDAR-Knight:CT?${Q}` }));
add('v2 URI port 99999', v2({ uri: `otpauth://totp:99999/LiDAR-Knight:CT?${Q}` }));
add('v2 URI port 0', v2({ uri: `otpauth://totp:0/LiDAR-Knight:CT?${Q}` }));
add('v2 URI port 00080', v2({ uri: `otpauth://totp:00080/LiDAR-Knight:CT?${Q}` }));
add('v2 URI port 20 digits', v2({ uri: `otpauth://totp:${'9'.repeat(20)}/LiDAR-Knight:CT?${Q}` }));
add('v2 URI empty port', v2({ uri: `otpauth://totp:/LiDAR-Knight:CT?${Q}` }));
// backslash (otpauth is not a special scheme: it is an ordinary character, never '/')
add('v2 URI backslash after host', v2({ uri: `otpauth://totp\\LiDAR-Knight:CT?${Q}` }));
add('v2 URI backslashes after scheme', v2({ uri: `otpauth:\\\\totp/LiDAR-Knight:CT?${Q}` }));
add('v2 URI backslash in host', v2({ uri: `otpauth://to\\tp/LiDAR-Knight:CT?${Q}` }));
add('v2 URI backslash before label', v2({ uri: `otpauth://totp/\\LiDAR-Knight:CT?${Q}` }));
add('v2 URI backslash in query', v2({ uri: `${L}?${Q}&x=\\` }));
add('v2 NAME backslash, raw label', v2({ name: 'A\\B', uri: `otpauth://totp/LiDAR-Knight:A\\B?${Q}` }));
add('v2 NAME backslash, encoded label', v2({ name: 'A\\B' }));
// ASCII tab (WHATWG removes it anywhere) and C0 controls (WHATWG strips them at both ends)
add('v2 URI tab in host', v2({ uri: `otpauth://to\ttp/LiDAR-Knight:CT?${Q}` }));
add('v2 URI tab in label', v2({ uri: `otpauth://totp/LiDAR-\tKnight:CT?${Q}` }));
add('v2 URI tab in secret', v2({ uri: `${L}?secret=ABCDE\tFGHIJKLMNOPQRSTUVWXYZ234567&issuer=LiDAR-Knight` }));
add('v2 URI tab in scheme', v2({ uri: `otp\tauth://totp/LiDAR-Knight:CT?${Q}` }));
add('v2 URI tab in parameter name', v2({ uri: `${L}?sec\tret=${S}&issuer=LiDAR-Knight` }));
add('v2 URI tab as user info', v2({ uri: `otpauth://\t@totp/LiDAR-Knight:CT?${Q}` }));
add('v2 URI empty user info', v2({ uri: `otpauth://@totp/LiDAR-Knight:CT?${Q}` }));
add('v2 URI leading U+0001', v2({ uri: `\u0001${L}?${Q}` }));
add('v2 URI trailing U+0001', v2({ uri: `${L}?${Q}\u0001` }));
add('v2 URI leading U+001F and space', v2({ uri: `\u001f ${L}?${Q}` }));
add('v2 URI trailing U+001C', v2({ uri: `${L}?${Q}\u001c` }));
add('v2 URI U+0001 in another value', v2({ uri: `${L}?${Q}&x=\u0001` }));
add('v2 URI U+0001 in label', v2({ uri: `otpauth://totp/LiDAR-Knight:C\u0001T?${Q}` }));
// percent escapes in the query: URLSearchParams decodes leniently (U+FFFD) and keeps a BOM
add('v2 URI %E2%82 in another value', v2({ uri: `${L}?${Q}&x=%E2%82` }));
add('v2 URI %E2%82 as another name', v2({ uri: `${L}?${Q}&%E2%82=1` }));
add('v2 URI %C3 in another value', v2({ uri: `${L}?${Q}&x=%C3` }));
add('v2 URI %FF in another value', v2({ uri: `${L}?${Q}&x=%FF` }));
add('v2 URI two malformed names', v2({ uri: `${L}?${Q}&%E2%82=1&%F0%9F=2` }));
add('v2 URI %C3%A9 in another value', v2({ uri: `${L}?${Q}&x=%C3%A9` }));
add('v2 URI stray % in another value', v2({ uri: `${L}?${Q}&x=%&y=%2G` }));
add('v2 URI %E2%82 in secret', v2({ uri: `${L}?secret=${S}%E2%82&issuer=LiDAR-Knight` }));
add('v2 URI encoded L in issuer', v2({ uri: `${L}?secret=${S}&issuer=%4CiDAR-Knight` }));
add('v2 URI plus in issuer', v2({ uri: `${L}?secret=${S}&issuer=LiDAR+Knight` }));
add('v2 URI empty parameters', v2({ uri: `${L}?&&${Q}&&` }));
// BOM (U+FEFF) in the label or the query
add('v2 URI raw BOM before label', v2({ uri: `otpauth://totp/\u{FEFF}LiDAR-Knight:CT?${Q}` }));
add('v2 URI %EF%BB%BF before label', v2({ uri: `otpauth://totp/%EF%BB%BFLiDAR-Knight:CT?${Q}` }));
add('v2 URI %ef%bb%bf before label', v2({ uri: `otpauth://totp/%ef%bb%bfLiDAR-Knight:CT?${Q}` }));
add('v2 URI raw BOM before secret name', v2({ uri: `${L}?\u{FEFF}${Q}` }));
add('v2 URI two BOMs before secret name', v2({ uri: `${L}?%EF%BB%BF%EF%BB%BF${Q}` }));
add('v2 URI %EF%BB%BF before secret value', v2({ uri: `${L}?secret=%EF%BB%BF${S}&issuer=LiDAR-Knight` }));
add('v2 URI BOM before issuer value', v2({ uri: `${L}?secret=${S}&issuer=%EF%BB%BFLiDAR-Knight` }));
add('v2 URI BOM in another value', v2({ uri: `${L}?${Q}&x=%EF%BB%BF` }));
add('v2 NAME with an inner BOM', v2({ name: 'A\u{FEFF}B' }));
// algorithm: JavaScript's toUpperCase also maps U+017F (long s) to S
add('v2 URI algorithm long-s ha1', v2({ uri: `${L}?secret=${S}&algorithm=\u{17F}ha1` }));
add('v2 URI algorithm sHa1', v2({ uri: `${L}?secret=${S}&algorithm=sHa1` }));
add('v2 URI algorithm SHA256', v2({ uri: `${L}?secret=${S}&algorithm=SHA256` }));
// dot segments before the label
add('v2 URI ../ before label', v2({ uri: `otpauth://totp/x/../LiDAR-Knight:CT?${Q}` }));
add('v2 URI %2E%2e/ before label', v2({ uri: `otpauth://totp/x/%2E%2e/LiDAR-Knight:CT?${Q}` }));
add('v2 URI ./ before label', v2({ uri: `otpauth://totp/./LiDAR-Knight:CT?${Q}` }));
// NAMEs a Uri path would rewrite (the card's label must stay the NAME)
for (const name of ['A/./B', 'A/../B', 'X/.', '..', 'A+B', 'Q?#&=+ /', 'Zo\u{EB} \u{1F680}']) add(`v2 NAME ${JSON.stringify(name)}`, v2({ name }));
add('v2 NAME A+B, raw label', v2({ name: 'A+B', uri: `otpauth://totp/LiDAR-Knight:A+B?${Q}` }));
// EMAIL: lower-case means JavaScript's toLowerCase leaves it unchanged
const letters = [
  0x00c0, 0x0130, 0x03a3, 0x037f, 0x0524, 0x052e, 0x10c7, 0x10cd, 0x13a0, 0x13f5, 0x1c89, 0x1c90, 0x1cbf, 0x1e9e, 0x2c2f,
  0x2c7e, 0xa7ae, 0xa7c0, 0xa7c5, 0xa7d0, 0xa7f5, 0x10400, 0x10570, 0x10c80, 0x118a0, 0x16e40, 0x1e900,
  0x00e9, 0x00df, 0x03c2, 0x0149, 0x2102, 0x13f8, 0x10428, 0x1e922,
];
for (const cp of letters) add(`v2 EMAIL a+U+${cp.toString(16).toUpperCase().padStart(4, '0')}`, v2({ email: `a${String.fromCodePoint(cp)}@example.com` }));
for (const [tag, ch] of [['U+180E', '\u{180E}'], ['U+FEFF', '\u{FEFF}'], ['U+00A0', '\u{A0}'], ['U+2028', '\u{2028}'], ['U+3000', '\u{3000}'], ['U+200B', '\u{200B}']]) {
  add(`v2 EMAIL a+${tag}`, v2({ email: `a${ch}b@example.com` }));
}

// A Dart string literal: '$' escaped, and every character outside printable ASCII written as an escape so the
// generated file shows each invisible character (BOM, joiners, spaces) explicitly.
const BS = String.fromCharCode(92);
const dartString = s => JSON.stringify(s)
  .replace(/\$/g, `${BS}$`)
  .replace(/[^\x20-\x7e]/gu, ch => `${BS}u{${ch.codePointAt(0).toString(16).toUpperCase()}}`);
const rows = cases.map(({ id, text }) => {
  const bytes = Buffer.from(text, 'utf8');
  const r = parseKeyFile(new Uint8Array(bytes));
  const f = r.ok ? r.fields : {};
  const props = [`id: ${dartString(id)}`, `b64: ${dartString(bytes.toString('base64'))}`];
  if (r.ok) {
    props.push(`format: ${r.format}`, `seat: ${dartString(f.seat)}`, `name: ${dartString(f.name)}`, `secret: ${dartString(f.secret)}`);
    if (r.format === 2) {
      props.push(`issuer: ${dartString(f.issuer)}`, `email: ${dartString(f.email)}`, `generation: ${f.generation}`,
        `issuedAt: ${dartString(f.issuedAt)}`, `activateBy: ${dartString(f.activateBy)}`, `activationId: ${dartString(f.activationId)}`);
    }
  } else props.push(`error: ${dartString(r.message)}`);
  return `  ParityCase(${props.join(', ')}),`;
});
writeFileSync(new URL('../test/lidar_key_file_parity_extra.dart', import.meta.url), `// GENERATED by scripts/lidar_key_file_parity.mjs from the server reference parseKeyFile
// (${label}), Node ${process.versions.node} (Unicode ${process.versions.unicode}), over SYNTHETIC files only
// (public test secrets, no owner key). Do not edit by hand: each row is the reference verdict the native parser
// must reproduce (contract v2.3). ${cases.length} rows: ${cases.filter((_, i) => rows[i].includes('format:')).length} accepted.

import 'lidar_key_file_parity_cases.dart';

const parityCasesExtra = <ParityCase>[
${rows.join('\n')}
];
`);
console.log(`${changed.length} code points in ${runs.length} runs; ${cases.length} extra rows`);
